#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-metrics
Version  : 3.1.5
Release  : 2
URL      : https://github.com/dropwizard/metrics/archive/v3.1.5.tar.gz
Source0  : https://github.com/dropwizard/metrics/archive/v3.1.5.tar.gz
Source1  : https://repo1.maven.org/maven2/com/yammer/metrics/metrics-parent/2.2.0/metrics-parent-2.2.0.pom
Source2  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.jar
Source3  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.pom
Source4  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-parent/3.1.5/metrics-parent-3.1.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-metrics-data = %{version}-%{release}

%description
Metrics [![Build Status](https://secure.travis-ci.org/dropwizard/metrics.png)](http://travis-ci.org/dropwizard/metrics)
=======

%package data
Summary: data components for the mvn-metrics package.
Group: Data

%description data
data components for the mvn-metrics package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/yammer/metrics/metrics-parent/2.2.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/yammer/metrics/metrics-parent/2.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.5
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.5


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/yammer/metrics/metrics-parent/2.2.0/metrics-parent-2.2.0.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.jar
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.5/metrics-parent-3.1.5.pom
