#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-metrics
Version  : 4.0.5
Release  : 9
URL      : https://github.com/dropwizard/metrics/archive/v4.0.5.tar.gz
Source0  : https://github.com/dropwizard/metrics/archive/v4.0.5.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.jar
Source2  : https://repo.maven.apache.org/maven2/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.pom
Source3  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2-sources.jar
Source4  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar
Source5  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.pom
Source6  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-core/4.0.5/metrics-core-4.0.5.jar
Source7  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-core/4.0.5/metrics-core-4.0.5.pom
Source8  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-graphite/3.1.5/metrics-graphite-3.1.5.jar
Source9  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-graphite/3.1.5/metrics-graphite-3.1.5.pom
Source10  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-json/3.1.5/metrics-json-3.1.5.jar
Source11  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-json/3.1.5/metrics-json-3.1.5.pom
Source12  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-jvm/3.1.5/metrics-jvm-3.1.5.jar
Source13  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-jvm/3.1.5/metrics-jvm-3.1.5.pom
Source14  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-parent/3.1.2/metrics-parent-3.1.2.pom
Source15  : https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-parent/4.0.5/metrics-parent-4.0.5.pom
Source16  : https://repo1.maven.org/maven2/com/yammer/metrics/metrics-parent/2.2.0/metrics-parent-2.2.0.pom
Source17  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/3.1.0/metrics-core-3.1.0.pom
Source18  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.jar
Source19  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.pom
Source20  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/3.2.4/metrics-core-3.2.4.jar
Source21  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/3.2.4/metrics-core-3.2.4.pom
Source22  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-parent/3.1.0/metrics-parent-3.1.0.pom
Source23  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-parent/3.1.5/metrics-parent-3.1.5.pom
Source24  : https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-parent/3.2.4/metrics-parent-3.2.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-metrics-data = %{version}-%{release}
Requires: mvn-metrics-license = %{version}-%{release}

%description
Metrics
=======
[![Build Status](https://secure.travis-ci.org/dropwizard/metrics.png)](http://travis-ci.org/dropwizard/metrics)
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/io.dropwizard.metrics/metrics-core/badge.svg)](https://maven-badges.herokuapp.com/maven-central/io.dropwizard.metrics/metrics-core/)
[![Code Climate](https://codeclimate.com/github/dropwizard/metrics/badges/gpa.svg)](https://codeclimate.com/github/dropwizard/metrics)

%package data
Summary: data components for the mvn-metrics package.
Group: Data

%description data
data components for the mvn-metrics package.


%package license
Summary: license components for the mvn-metrics package.
Group: Default

%description license
license components for the mvn-metrics package.


%prep
%setup -q -n metrics-4.0.5

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-metrics
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-metrics/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/yammer/metrics/metrics-core/2.2.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/yammer/metrics/metrics-core/2.2.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/4.0.5
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/4.0.5/metrics-core-4.0.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/4.0.5
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/4.0.5/metrics-core-4.0.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-graphite/3.1.5
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-graphite/3.1.5/metrics-graphite-3.1.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-graphite/3.1.5
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-graphite/3.1.5/metrics-graphite-3.1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-json/3.1.5
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-json/3.1.5/metrics-json-3.1.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-json/3.1.5
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-json/3.1.5/metrics-json-3.1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-jvm/3.1.5
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-jvm/3.1.5/metrics-jvm-3.1.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-jvm/3.1.5
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-jvm/3.1.5/metrics-jvm-3.1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.2
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.2/metrics-parent-3.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/4.0.5
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/4.0.5/metrics-parent-4.0.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/yammer/metrics/metrics-parent/2.2.0
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/com/yammer/metrics/metrics-parent/2.2.0/metrics-parent-2.2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.0
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.0/metrics-core-3.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.2.4
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.2.4/metrics-core-3.2.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.2.4
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.2.4/metrics-core-3.2.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.0
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.0/metrics-parent-3.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.5
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.5/metrics-parent-3.1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.2.4
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.2.4/metrics-parent-3.2.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.jar
/usr/share/java/.m2/repository/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.pom
/usr/share/java/.m2/repository/com/yammer/metrics/metrics-parent/2.2.0/metrics-parent-2.2.0.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.0/metrics-core-3.1.0.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2-sources.jar
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.jar
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.2.4/metrics-core-3.2.4.jar
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/3.2.4/metrics-core-3.2.4.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/4.0.5/metrics-core-4.0.5.jar
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-core/4.0.5/metrics-core-4.0.5.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-graphite/3.1.5/metrics-graphite-3.1.5.jar
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-graphite/3.1.5/metrics-graphite-3.1.5.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-json/3.1.5/metrics-json-3.1.5.jar
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-json/3.1.5/metrics-json-3.1.5.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-jvm/3.1.5/metrics-jvm-3.1.5.jar
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-jvm/3.1.5/metrics-jvm-3.1.5.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.0/metrics-parent-3.1.0.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.2/metrics-parent-3.1.2.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.1.5/metrics-parent-3.1.5.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/3.2.4/metrics-parent-3.2.4.pom
/usr/share/java/.m2/repository/io/dropwizard/metrics/metrics-parent/4.0.5/metrics-parent-4.0.5.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-metrics/LICENSE
